language: python
python: 2.7
env:
  - TOX_ENV=py27-django1.7
  - TOX_ENV=py26-django1.6
  - TOX_ENV=py27-django1.6
  - TOX_ENV=py26-django1.5
  - TOX_ENV=py27-django1.5
  - TOX_ENV=py26-django1.4
  - TOX_ENV=py27-django1.4
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
